vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

vim.opt.termguicolors = true
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.softtabstop = 0
vim.opt.smarttab = true
vim.opt.expandtab = true
vim.opt.mouse = 'a'
vim.opt.updatetime = 1000
vim.opt.hidden = true
vim.opt.cmdheight = 2
vim.wo.number = true
vim.o.background = 'dark'
vim.opt.clipboard = 'unnamedplus'
vim.opt.fixendofline = false
vim.opt.backup = false
vim.opt.writebackup = false
vim.cmd('set shortmess+=c')
vim.opt.spell = true
vim.opt.spelllang = { 'en_us' }
vim.opt.spelloptions = 'camel'
